# Generated by Django 4.0.2 on 2023-09-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(unique=True)),
                ('title_without_series', models.CharField(max_length=128)),
                ('book_description', models.CharField(max_length=3000)),
                ('publication_year', models.CharField(max_length=128)),
                ('publisher', models.CharField(max_length=128)),
                ('book_average_rating', models.FloatField(null=True)),
                ('cover_page', models.URLField()),
                ('book_url', models.URLField()),
            ],
        ),
    ]
