# Generated by Django 4.0.2 on 2023-09-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='rotation_state',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True),
        ),
    ]
