# Generated by Django 4.0.2 on 2023-09-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrec', '0002_choice_survey_submission_question_choice_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
