# Generated by Django 4.0.2 on 2023-09-27 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookrec', '0002_submission_rotation_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='rotation_state',
        ),
    ]
