# Generated by Django 4.0.2 on 2023-09-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrec', '0003_remove_submission_rotation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='rotation_state',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
