# Generated by Django 4.0.2 on 2023-09-09 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookrec', '0004_survey_rotation_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
