# Generated by Django 4.0.2 on 2023-09-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrec', '0004_submission_rotation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='rotation_state',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True),
        ),
    ]
