# Generated by Django 4.0.2 on 2023-10-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrec', '0004_rename_sessionid_surveyresponse_sessionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation_order', models.JSONField(default=list)),
                ('current_index', models.IntegerField(default=0)),
            ],
        ),
    ]
