# Generated by Django 4.0.2 on 2023-09-09 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookrec', '0005_remove_question_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookrec.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookrec.question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookrec.survey')),
            ],
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
