# Generated by Django 4.0.2 on 2023-09-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrec', '0007_submission_delete_surveyresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=models.CharField(max_length=6000),
        ),
    ]
